# Your Solution
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers: 
      - name: project4-book
        image: book-catalog:1
        ports:
         - containerPort: 8000
        imagePullPolicy:  IfNotPresent
        env:
        - name: DATABASE_URL
          value: "postgresql://pbarnes_sit722_part3_user:ZtR1W9q8Yc4p7exIu6APMAD1eI2GNP5I@dpg-creiqljv2p9s73cvj2l0-a.singapore-postgres.render.com/pbarnes_sit722_part3"
---
apiVersion: v1
kind: Service
metadata:
  name: book-front
spec:
  selector:
    app: book-front
  type: LoadBalancer 
  ports:
  - protocol: TCP
    targetPort: 8000
    port: 80