# Your Solution
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers: 
      - name: project4-book
        image: book-catalog:1
        ports:
         - containerPort: 8000
        imagePullPolicy:  IfNotPresent
        env:
        - name: DATABASE_URL
          value: "postgresql://pbarnessit722part4:MiAUg5zMP01P4FeF9hlZwXCLryaMEZER@dpg-crr4cg56l47c73ccqhf0-a.oregon-postgres.render.com/pbarnessit722part4"
---
apiVersion: v1
kind: Service
metadata:
  name: book-front
spec:
  selector:
    app: book-front
  type: LoadBalancer 
  ports:
  - protocol: TCP
    targetPort: 8000
    port: 80
